### ISSUE TITLE
Not compatible with parcel-plugin-ogimage

### ISSUE THREAD

**Issue by Grawl** [shff/parcel-plugin-inliner#13] opened 2020-01-28 14:47 UTC
[`parcel-plugin-ogimage`](https://github.com/lukechilds/parcel-plugin-ogimage) uses `--public-url` for URL  transforming but `parcel-plugin-inliner` uses this option for local files resolving. So I cannot use both plugins.

https://github.com/lukechilds/parcel-plugin-ogimage/issues/7

**Comment by shff** [comment] 2020-02-06 17:08
Do you have any example of how to trigger this error?

**Comment by shff** [comment] 2020-02-06 18:15
Okay, I removed the need for `--public-url` in 75e1254c1090513d905550bd249c781b116d4030. It was actually easier than I thought. I also pushed the changes to NPM, so all you have to do is update the package.

However I'm still not being able to make the two plugins work together. The problem is that PostHTML (which my plugin uses) takes longer to finish than `parcel-plugin-ogimage`.

```
🐨 yarn parcel build index.html
yarn run v1.19.1
warning package.json: No license field
$ /Users/ferreira.silvio/Code/blaa/node_modules/.bin/parcel build index.html
✨  Built in 342ms.

dist/card.bdd59de1.png       40.77 KB    20ms
dist/blaa.d364822e.js         1.13 KB    27ms
dist/index.html                 267 B    17ms
dist/blaa.d364822e.js.map       186 B    17ms
Started inlining

✨  Fixed og:image link in 5ms.
Finishing inlining
✨  Done in 1.43s.
```

**Comment by Grawl** [comment] 2020-02-07 01:36
There is a way to control plugins run sequence?

**Comment by shff** [comment] 2020-02-07 10:41
Not that I know of, but I'll keep investigating. I don't have much control due to the way both Parcel and PostHTML work :(

**Comment by shff** [comment] 2021-01-17 17:50
After some chatting with Parcel experts this would require changes in Parcel code itself. Sorry about that. I'll be closing the issue since there isn't much to be done from my side. :(

**Closed as completed by shff** 2021-01-17 17:50 UTC
