### ISSUE TITLE
changes to assets during `parcel watch` don't propagate to inlined copies

### ISSUE THREAD

**Issue by Lx** [shff/parcel-plugin-inliner#12] opened 2019-11-13 12:00 UTC
## Steps to reproduce

1.  Set up a simple `index.html` file referencing an `index.ts` file.
2.  Put something in the `index.ts` file that affects page display.
3.  **Without** `parcel-plugin-inliner` installed, run `parcel watch --public-url . index.html`.
4.  Observe the thing from `index.ts` that affects page display, such as:

    ```typescript
    document.body.append('XXX');
    ```

5.  Comment out that thing in `index.ts`.
6.  Reload the page, and observe that the thing is no longer visible.
7.  Terminate the `parcel watch` process.
8.  Reinstate the thing in `index.ts`.
9.  **With** `parcel-plugin-inliner` installed, run `parcel watch --public-url . index.html `.
10.  Observe the thing from `index.ts` that affects page display.
11.  Comment out that thing in `index.ts`.
12.  Observe that the page reloads, **but the thing remains visible**.

## Expected result

Inlined assets update as the `parcel watch` process rebuilds them.

**Comment by shff** [comment] 2019-11-24 20:26
Thanks for filing the issue!

That happens because `parcel-plugin-inliner` rewrites the HTML file on the first time it runs.

When you change the JS file, it doesn't know what to inline because there are not `src` attributes in `<script>` tags anymore. A workaround is re-saving `index.html`.

#### A possible solution

A way to make it work without workarounds would be to add an extra attribute to the inlined `<script>` tag with the original address, which then would be re-processed later...

The code responsible for that is in a dependency, but since it's unmaintained and had some bugs  (the owner is not merging pull requests) I had to fork it anyway.

Here's a preliminary idea that actually works: https://github.com/shff/posthtml-inline-assets/pull/1

The problem is that this generates metadata junk in the resulting HTML, and should be stripped in production (non-watch) builds. I'll have to pass a parameter from `parcel-plugin-inliner` to `posthtml-inline-assets` depending on whether you're running `parcel watch` or a `parcel build`.

That's probably not that hard, I will look into that!

**Comment by shff** [comment] 2020-03-15 00:57
I disabled non-production builds by default in v1.0.14. Closing this ticket.

**Closed as completed by shff** 2020-03-15 00:57 UTC
